repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: ["--disable", "MD013"]  # allow long lines for now

  - repo: https://github.com/lycheeverse/lychee
    rev: v0.14.5
    hooks:
      - id: lychee
        args:
          - "--no-progress"
          - "--exclude-mail"
